apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
  name: bookinfo-gateway
  namespace: bookinfo
spec:
  gatewayClassName: my-gateway-class
  listeners:
    - name: bookinfo
      # hostname: "*.costalong.cn"
      protocol: HTTP
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: bookinfo-http
  namespace: bookinfo
  labels:
    app: traefik
spec:
  parentRefs:
  - name: bookinfo-gateway
  hostnames: 
   - bookinfo.costalong.cn 
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /productpage
    - path:
        type: PathPrefix
        value: /static
    - path: 
        type: PathPrefix
        value: /login
    - path:
        type: PathPrefix
        value: /logout
    - path:
        type: PathPrefix
        value: /api/v1/products
    backendRefs:
    - name: productpage
      port: 9080
      weight: 1
---
#apiVersion: networking.istio.io/v1alpha3
#kind: VirtualService
#metadata:
#  name: bookinfo
#  namespace: bookinfo
#spec:
#  hosts:
#  - "bookinfo.costalong.cn"
#  gateways:
#  - bookinfo-gateway
#  http:
#  - match:
#    - uri:
#        exact: /productpage
#    - uri:
#        prefix: /static
#    - uri:
#        exact: /login
#    - uri:
#        exact: /logout
#    - uri:
#        prefix: /api/v1/products
#    route:
#    - destination:
#        host: productpage
#        port:
#          number: 9080
