apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
  name: kiali-gateway
  namespace: istio-system
spec:
  gatewayClassName: my-gateway-class
  listeners:
    - name: http
      protocol: HTTP
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: kiali-http
  namespace: istio-system
  labels:
    app: traefik
spec:
  parentRefs:
    - name: kiali-gateway
  hostnames:
    - kiali.costalong.cn
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
    - backendRefs:                          # [14]
        - name: kiali                  # [15]
          weight: 1                         # [16]
          port: 20001


---
#apiVersion: gateway.networking.k8s.io/v1alpha2
#kind: HTTPRoute
#metadata:
#  name: jaeger-http
#  namespace: istio-system
#  labels:
#    app: traefik
#spec:
#  parentRefs:
#    - name: jaeger-gateway
#  hostnames:
#    - jaeger.costalong.cn
#  rules:
#    - matches:
#        - path:
#            type: PathPrefix
#            value: /
#    - backendRefs:                          # [14]
#        - name: tracing                  # [15]
#          weight: 1                         # [16]
#          port: 80
