apiVersion: apps/v1
kind: Deployment
metadata:
  name: oss-static
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template: 
    metadata:
      labels:
        app: nginx
    spec: 
      nodeSelector:
        k8s.aliyun.com/vnode: "true"
      tolerations:
      - key: k8s.aliyun.com/vnode
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumesMounts:
          - name: pov-oss
            mountPath: "/data"
        volumes:
          - name: pvc-oss
            persistentVolumeClaim:
              claimName: pvc-oss
          


    
