apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-oss
  labels:
    aliclound-pvname: pv-oss
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  flexVolume:
    driver: "alicloud/oss"
    options:
      bucket: "costa92"
      url: "oss-cn-hangzhou.aliyuncs.com"
      otherOpts: "-o max_stat_cache_size=0 -o allow_other"
      path: "/k8s/data"
      ramRole: "k8s-pv"
